export const Unani = [
  {
    "scientific_name": "Acalypha indica L",
    "common_name": "Indian-nettle, copperleaf",
    "type_of_disorder": "Neuroinflammation, Alzheimer",
    "components": "Hydroxybenzoate, Flavonoids, Lactone, Tocopherol",
    "compound": "Catechin, Rutin, Kaempferol, Naringenin, Gallic acid, Deoxykhivorin, Vitamin E",
    "part": "Leaves, Root and stem",
    "region_found": "Assam, Bihar, Mahrastra, Odisha, Rajasthan",
    "reference": "https://phcogrev.com/article/2021/15/30/105530phrev20211516",
    "image": "Acalypha_indica_L.jpeg"
  },
  {
    "scientific_name": "Achyranthes aspera L.",
    "common_name": "Prickly chaff flower",
    "type_of_disorder": "Epilepsy, paralysis",
    "components": "sterols alkaloids, tannins, saponins, sapogenins, cardiac glycosides, ecdysterone, flavonoids and phenolic etc",
    "compound": "Betaine, achyranthine, hentriacontane, ecdysterone, achyranthes saponins A, B, C, D",
    "part": "Whole plant",
    "region_found": "Assam, Bihar, Gujarat, Karnataka, Madhya Pradesh, Odisha, Rajasthan, South India, Uttar Pradesh",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1572498319.pdf",
    "image": "Achyranthes_aspera_L.jpeg"
  },
  {
    "scientific_name": "Asparagus racemosus",
    "common_name": "Satawari",
    "type_of_disorder": "Anxiety and Related disorders",
    "components": "polycyclic alkaloids, flavanoids",
    "compound": "alkaloids (Asparagamine A), Isoflavones-8- methoxy-5, 6, 4-trihydroxy isoflavone-7-0-beta-D-glucopyranoside, Flavonoids (Kaempferol, quercetin, rutin), shatavaroside, secoisolariciresinol, immunosides, beta sitosterol, sitigmaterol, daidzein, genistein, racemoside A-C and other compounds like essential oils, resins, tannins, tyrosine, arginine, asparagine",
    "part": "Root",
    "region_found": "Arunachal Pradesh, Assam, Chhattisgarh, Delhi, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Kerala and Punjab",
    "reference": "https://www.plantsjournal.com/archives/2021/vol9issue4/PartB/9-4-23-980.pdf",
    "image": "Asparagus_racemosus.jpeg"
  },
  {
    "scientific_name": "Atropa belladonna",
    "common_name": "Angurshafa",
    "type_of_disorder": "Parkinson's disease",
    "components": "Alkaloids",
    "compound": "atropine, hyoscyamine, and scopolamine",
    "part": "Root, leaves, and fruit",
    "region_found": "Kashmir and Himachal Pradesh up to 2,500 m",
    "reference": "https://pubmed.ncbi.nlm.nih.gov/32662978/",
    "image": "Atropa_belladonna.jpeg"
  },
  {
    "scientific_name": "Bacopa monneri",
    "common_name": "Brahmi",
    "type_of_disorder": "DEMENTIA",
    "components": "Saponins",
    "compound": "Bacosides",
    "part": "Stem and leaves",
    "region_found": "North eastern regions",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Bacopa_monneri.jpeg"
  },
  {
    "scientific_name": "Boerhaavia diffusa",
    "common_name": "Punarnava",
    "type_of_disorder": "Huntington's Disease",
    "components": "Alkaloids, Phenolic compounds",
    "compound": "Punarnavine, caffeoyltartaric acid",
    "part": "Roots",
    "region_found": "northeastern parts of India, including the Amaravathi village in Guntur district",
    "reference": "https://onlinelibrary.wiley.com/doi/abs/10.1002/9783527803781.ch8",
    "image": "Boerhaavia_diffusa.jpeg"
  },
  {
    "scientific_name": "Boswellia serrata",
    "common_name": "Indian frankincense, Indian olibanum, Salai guggul, Shallaki, Parangi, Saambraa",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Triterpenes",
    "compound": "pentacyclic triterpene acids, β-boswellic acid and the acetylboswellic acids",
    "part": "Resin",
    "region_found": "Andhra Pradesh, Gujarat, Madhya Pradesh, Jharkhand, and Chhattisgarh",
    "reference": "https://pubmed.ncbi.nlm.nih.gov/30396086/",
    "image": "Boswellia_serrata.jpeg"
  },
  {
    "scientific_name": "Brassica oleracea L. var. italica",
    "common_name": "Broccoli sprouts",
    "type_of_disorder": "Autism",
    "components": "Isothiocyanate",
    "compound": "Sulforaphane",
    "part": "Broccoli Sprout",
    "region_found": "Tamil Nadu",
    "reference": "https://www.florajournal.com/archives/2021/vol9issue3/PartA/9-1-13-226.pdf",
    "image": "Brassica_oleracea_L_var_italica.jpeg"
  },
  {
    "scientific_name": "Celastrus paniculatus Wild",
    "common_name": "Jyotishmati",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "Celastrine",
    "part": "Seeds",
    "region_found": "Punjab, Kashmir, Western Ghats, Eastern Ghats, Rajmahal hills in Bihar and Orissa,  Simlipal Biosphere Reserve Forest, Karlapat Sanctuary, Niyamgiri hills",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Celastrus_paniculatus_Wild.jpeg"
  },
  {
    "scientific_name": "Centella asiatica (L.) Urb.",
    "common_name": "Asiatic pennywort",
    "type_of_disorder": "Memory loss, mental disorder, insanity",
    "components": "Triterpenoids",
    "compound": "asiaticoside, madecassoside, asiatic acid, and madecassic acid",
    "part": "Leaves",
    "region_found": "throughout India growing in moist places up to an altitude of 1800 m.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Centella_asiatica_(L.)_ Urb.jpeg"
  },
  {
    "scientific_name": "Clerodendrun capitatum Schum & Thonn",
    "common_name": "glorybower, bagflower, and bleeding-heart",
    "type_of_disorder": "Brain disorder, epilepsy",
    "components": "alkaloid, tannins, saponins, Flavonoids, Triterpenoid, sapoinin, glycosides",
    "compound": "flavones saponins, triterpenes, sesquiterpenes, anthraquinone, iridoid glycosides, lupeol clerodendrin, phytosterols, ferulic acid, arabinose, ,",
    "part": "Roots, leaves, seeds",
    "region_found": "Maharashtra : Thane district",
    "reference": "https://www.bing.com/ck/a?!&&p=c9000cfd2e4ed045JmltdHM9MTcxMTIzODQwMCZpZ3VpZD0wMzkwMGUzYi02Nzg0LTY1NzUtM2EwMy0xYTE0NjY3NjY0ZDEmaW5zaWQ9NTIxNQ&ptn=3&ver=2&hsh=3&fclid=03900e3b-6784-6575-3a03-1a14667664d1&psq=SOME+MEDICINAL+PLANTS+OF+THE+FAMILY+VERBENACEAE+COMMONLY+USED+IN+JOS%2c+NIGERIA+-+A+REVIEW+*IBRAHIM%2c+Jemilat+Aliyu1%3b+EGHAREVBA%2c+Henry+Omoregie1%3b+OBOKAYI%2c+Oche+Deborah2%3b+KUNLE%2c+Oluyemisi+Folashade1&u=a1aHR0cHM6Ly93d3cucmVzZWFyY2hnYXRlLm5ldC9wdWJsaWNhdGlvbi8zMjQwMzQ5NTlfU09NRV9NRURJQ0lOQUxfUExBTlRTX09GX1RIRV9GQU1JTFlfVkVSQkVOQUNFQUVfQ09NTU9OTFlfVVNFRF9JTl9KT1NfTklHRVJJQS1BX1JFVklFVw&ntb=1",
    "image": "Clerodendrun_capitatum.jpeg"
  },
  {
    "scientific_name": "Clitoria ternatea",
    "common_name": "Aparajita",
    "type_of_disorder": "DEMENTIA",
    "components": "amino acids, proteins and carbohydrates",
    "compound": "",
    "part": "Roots",
    "region_found": "Andaman and Nicobar Islands, Andhra Pradesh, Assam, Bihar, Gujarat, Haryana, Karnataka,Kerala, Madhya Pradesh, Maharashtra, Manipur, Rajasthan, Tamil Nadu, Uttar Pradesh, West Bengal",
    "reference": "https://www.researchgate.net/profile/Dilip_Murthy2/publication/10984268_Clitoria_ternatea_root_extract_enhances_acetylcholine_content_in_rat_hippocampus/links/5a3c9d7e0f7e9b10e23bf5fc/Clitoria-ternatea-root-extract-enhances-acetylcholine-content-in-rat-hippocampus.pdf",
    "image": "Clitoria_ternatea.jpeg"
  },
  {
    "scientific_name": "Convolvulus pluricaulis",
    "common_name": "Shankhpushpi",
    "type_of_disorder": "Alzheimer's",
    "components": "Coumarins",
    "compound": "Scopoletin",
    "part": "leaves, flowers, stem, roots, seeds and ashes",
    "region_found": "Bihar and Punjab",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Convolvulus_pluricaulis.jpeg"
  },
  {
    "scientific_name": "Curcuma longa",
    "common_name": "Turmeric",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "Curcuminoids",
    "part": "Rhizome",
    "region_found": "Andhra Pradesh, Tamil Nadu, Orissa, Karnataka, West Bengal, Gujarat, Meghalaya, Maharashtra, Assam",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Curcuma_longa.jpeg"
  },
  {
    "scientific_name": "Cyperus rotundus L.",
    "common_name": "Purple nutsedge",
    "type_of_disorder": "epilepsy",
    "components": "Sesquiterpenoid, essential oil",
    "compound": "?-Cyperone,terpinen-4-ol",
    "part": "Root",
    "region_found": "Assam, Madhya Pradesh",
    "reference": "https://www.researchgate.net/publication/330434078_Unani_Perspective_and_New_Researches_of_Sa'ad_ku'fi_Cyperus_rotundus_A_Review",
    "image": "Cyperus_rotundus_L.jpeg"
  },
  {
    "scientific_name": "Delphinium denudatum Wall.",
    "common_name": "Jadwar",
    "type_of_disorder": "Anticonvulsants",
    "components": "alkaloids",
    "compound": "Isoxylitone,ethanolic extract",
    "part": "Dried root",
    "region_found": "Northern Western Ghats of Maharashtra",
    "reference": "https://www.researchgate.net/publication/345132007_Jadwar_Delphinium_denudatum_Wall_a_medicinal_plant",
    "image": "Delphinium_denudatum_Wall.jpeg"
  },
  {
    "scientific_name": "Ferula asafoetida L",
    "common_name": "Hing",
    "type_of_disorder": "Neurological disorders",
    "components": "phenolic",
    "compound": "carbohydrate and ferulic acid",
    "part": "dried latex, rhizome and root",
    "region_found": "Kashmir and parts of Punjab, and is also available in the Indian Himalayan region",
    "reference": "https://www.bing.com/ck/a?!&&p=3708683ed4ec20ffJmltdHM9MTcxMTA2NTYwMCZpZ3VpZD0wMzkwMGUzYi02Nzg0LTY1NzUtM2EwMy0xYTE0NjY3NjY0ZDEmaW5zaWQ9NTIxOQ&ptn=3&ver=2&hsh=3&fclid=03900e3b-6784-6575-3a03-1a14667664d1&psq=Review+on+ayurvedic+plant+based+compounds+to+cure+the+neurological+disorders+Siba+Pattanaik+and+Deoraj+Sharma&u=a1aHR0cHM6Ly93d3cucmVzZWFyY2hnYXRlLm5ldC9wdWJsaWNhdGlvbi8zNjg2MjIxOTBfUmV2aWV3X29uX2F5dXJ2ZWRpY19wbGFudF9iYXNlZF9jb21wb3VuZHNfdG9fY3VyZV90aGVfbmV1cm9sb2dpY2FsX2Rpc29yZGVycw&ntb=1",
    "image": "Ferula_asafoetida_L.jpeg"
  },
  {
    "scientific_name": "Foeniculum vulgare Mill",
    "common_name": "common fennel",
    "type_of_disorder": "cognitive function and memory",
    "components": "phenylpropene",
    "compound": "Anethole",
    "part": "Fruits and seed",
    "region_found": "Gujarat, Rajasthan, Karnataka, Maharashtra, Punjab, and Bihar",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Foeniculum_vulgare_Mill.jpeg"
  },
  {
    "scientific_name": "Hyoscyamus Niger",
    "common_name": "black henbane",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "hyoscyamine, scopolamine and tropane",
    "part": "Flower",
    "region_found": "assam and arunachal pradesh",
    "reference": "https://doi.org/10.33545/27072827.2023.v4.i1a.65",
    "image": "Hyoscyamus_Niger.jpeg"
  },
  {
    "scientific_name": "Moringa oleifera",
    "common_name": "drumstick tree",
    "type_of_disorder": "DEMENTIA",
    "components": "phenolic compounds and flavonoids",
    "compound": "",
    "part": "Leaves",
    "region_found": "Northwest India",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Moringa_oleifera.jpeg"
  },
  {
    "scientific_name": "Myristica fragrans Houtt.",
    "common_name": "Nutmeg",
    "type_of_disorder": "Nervous disorder",
    "components": "Phenolic compound",
    "compound": "Myristicin",
    "part": "Fruits",
    "region_found": "Madras and Southern India, Nilgiri hills, Coimbatore, Salem, Ramanathapuram, Tirunelveli, Kanya Kumari and Madurai districts, Malabar Coast, Assam and in other states.",
    "reference": "https://www.academia.edu/75411859/Nutmegs_and_wild_nutmegs_An_update_on_ethnomedicines_phytochemicals_pharmacology_and_toxicity_of_the_Myristicaceae_species",
    "image": "Myristica_fragrans_Houtt.jpeg"
  },
  {
    "scientific_name": "Nardostachys jatamansi",
    "common_name": "Sugandhbala",
    "type_of_disorder": "Psychotic disorders",
    "components": "Flavonoids",
    "compound": "4-amino-5-mercapto-3-substituted-1, 2, 4-triazole",
    "part": "Root Extract",
    "region_found": "subtropical and temperate Himalaya",
    "reference": "https://www.researchgate.net/publication/281550536_DIETARY_SUPPLEMENTATION_OF_NATURAL_AND_SYNTHETIC_PRODUCTS_REDUCES_ANXIETY_IN_MICE_AGAINST_ELECTRON_BEAM_RADIATION_INDUCED_OXIDATIVE_STRESS",
    "image": "Nardostachys_jatamansi.jpeg"
  },
  {
    "scientific_name": "Nigella sativa L.",
    "common_name": "Black seed, black cumin, kalonji",
    "type_of_disorder": "CNS Disorders",
    "components": "Phenolic compound",
    "compound": "Thymoquinone",
    "part": "Fruit",
    "region_found": "Punjab, Himachal Pradesh, Madhya Pradesh, Assam, West Bengal, Jharkhand, and Bihar",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Nigella_sativa_L.jpeg"
  },
  {
    "scientific_name": "Ocimum gratissimum L.",
    "common_name": "Tulsi or clove basil",
    "type_of_disorder": "Paralysis, mental disorder (Be), headache",
    "components": "phenylpropanoid",
    "compound": "Eugenol",
    "part": "Leaves and seed",
    "region_found": "Kerala",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Ocimum_gratissimum_L.jpeg"
  },
  {
    "scientific_name": "Panax ginseng",
    "common_name": "Ashwagandha",
    "type_of_disorder": "Parkinson's disease, Alzheimer's disease",
    "components": "steroid saponin",
    "compound": "Ginsenosides",
    "part": "Roots",
    "region_found": "eastern states of India's Himalayan regions, including Arunachal Pradesh, Manipur, Meghalaya, Sikkim, and West Bengal",
    "reference": "https://www.mdpi.com/1420-3049/24/16/2939",
    "image": "Panax_ginseng.jpeg"
  },
  {
    "scientific_name": "Passiflora incarnata",
    "common_name": "maypop",
    "type_of_disorder": "Anxiety and related disorders",
    "components": "alkaloids, flavanoids",
    "compound": "alkaloids(harmol, harman, harmine, harmaline and harmalol, flavonoids (Chrysin, benzoflavone, apigenin, orientin, isoorientin, vitexin, and isovitexin)",
    "part": "Leaves and stem",
    "region_found": "North East region of India",
    "reference": "https://www.plantsjournal.com/archives/2021/vol9issue4/PartB/9-4-23-980.pdf",
    "image": "Passiflora_incarnata.jpeg"
  },
  {
    "scientific_name": "Phyllanthus emblica L.",
    "common_name": "Amla",
    "type_of_disorder": "Epilepsy, Alzheimer's disease, memory enhance",
    "components": "polyphenolic compounds",
    "compound": "Tannins",
    "part": "Fruit",
    "region_found": "central and southern India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Phyllanthus_emblica L.jpeg"
  },
  {
    "scientific_name": "Portulaca oleracea",
    "common_name": "luni-bhaji or kulfa",
    "type_of_disorder": "CNS Disorders",
    "components": "Alpha-linolenic acid (ALA)",
    "compound": "Omega-3 fatty acid",
    "part": "leaves",
    "region_found": "India",
    "reference": "https://www.thepharmajournal.com/archives/?year=2019&vol=8&issue=6&ArticleId=3554",
    "image": "Portulaca_oleracea.jpeg"
  },
  {
    "scientific_name": "Premna integrifolia",
    "common_name": "Araṇi or Agnimantha",
    "type_of_disorder": "Parkinson's disease",
    "components": "Alkaloid, Diterpene, Volatile, Flavonoid, Cardiac glycoside",
    "compound": "Premnine, ganiarine, permnzole, clerodendrin A, Quercetin, Digoxin analogue.",
    "part": "Root",
    "region_found": "Forest of South India and West Bengal (Northern part),  plains of Maharashtra, Gujarat, North Karnataka, Assam, Khasi hills and Tarai",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4623632/",
    "image": "Premna_integrifolia.jpeg"
  },
  {
    "scientific_name": "Prunus amygdalus Dulcis",
    "common_name": "Badam",
    "type_of_disorder": "memory loss, insomnia, and headache",
    "components": "Phenolic Compounds, Protiens",
    "compound": "Vitamin E, Omega-3 fatty acids, Melatonin, Riboflavin (Vitamin B2",
    "part": "Seeds",
    "region_found": "Kashmir,  Maharashtra, Karnataka, Tamil Nadu, Andhra Pradesh, and Kerala",
    "reference": "https://pubmed.ncbi.nlm.nih.gov/20871769/",
    "image": "Prunus_amygdalus_Dulcis.jpeg"
  },
  {
    "scientific_name": "Rauwolfia serpentina",
    "common_name": "Indian snakeroot, serpentine wood, sarpagandha, Patalagardi, and Chotachand",
    "type_of_disorder": "Anxiety, epilepsy, Nervous disorder",
    "components": "alcohols, alkaloids, glycosides, fatty acids, flavonoids, oleoresins, phytosterols, sugars, steroids and tannins",
    "compound": "ajmalidine, ajmaline, ajmalinine, ajmalicine, aricine, canescine, coryanthine, deserpidine, isoajmaline, isoserine, isoserpiline, lankanescine, neoajmaline, papaverine, raubasine, raucaffricine, rauhimbine, rauwolfinine, recanescine, rescinnamine, reserpiline, reserpine, reserpinine, sarpagine, serpentine, serpentinine, thebaine, yohimbine and yohimbinine",
    "part": "Whole plant",
    "region_found": "the sub-Himalayan region, Assam, the lower hills of the Gangetic plains, the eastern and western ghats, some parts of central India, and the Andamans.",
    "reference": "https://www.researchgate.net/profile/Rajendra-Bhanwaria/publication/346521741_Indian_Snake_Root_and_Devil_Root_as_Distinctive_Medicinal_Plant_for_Curing_Human_Disease_Biology_Chemistry_and_Cultivation_Practices_of_Rauwolfia_serpentina_and_Rauwolfia_tetraphylla/links/5fc6077492851c30129975fa/Indian-Snake-Root-and-Devil-Root-as-Distinctive-Medicinal-Plant-for-Curing-Human-Disease-Biology-Chemistry-and-Cultivation-Practices-of-Rauwolfia-serpentina-and-Rauwolfia-tetraphylla.pdf",
    "image": "Rauwolfia_serpentina.jpeg"
  },
  {
    "scientific_name": "Ruta angustifolia Pers.",
    "common_name": "narrow-leaved fringed rue",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Alkaloids",
    "compound": "Graveolinine",
    "part": "whole plant",
    "region_found": "throughout india",
    "reference": "https://www.mdpi.com/2223-7747/12/4/827",
    "image": "Ruta_angustifolia_Pers.jpeg"
  },
  {
    "scientific_name": "Salvia haematodes",
    "common_name": "Lal Behman",
    "type_of_disorder": "Alzheimer's disease",
    "components": "flavonoids, tannins, phenols, alkaloids, carbohydrates, sterols and essential oils",
    "compound": "bioflavonoid,1,8-cineole, linalool, a- and b-pinene, carvacrol, luteolin",
    "part": "Root",
    "region_found": "Uttar Pradesh",
    "reference": "https://pubmed.ncbi.nlm.nih.gov/29034195/",
    "image": "Salvia_haematodes.jpeg"
  },
  {
    "scientific_name": "Terminalia arjuna (Roxb.) Wight & Arn.",
    "common_name": "Arjun Tree",
    "type_of_disorder": "Nervous debility",
    "components": "Triterpenoid saponin",
    "compound": "arjunolic acid",
    "part": "Bark",
    "region_found": "Uttar Pardesh, South Bihar, Madhya Pradesh, Delhi and Deccan region",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Terminalia_arjuna_(Roxb.)_Wight_&_Arn.jpeg"
  },
  {
    "scientific_name": "Valeriana officinalis",
    "common_name": "garden heliotrope, common valerian, and all-heal",
    "type_of_disorder": "Attention Deficit Hyperactivity Disorder (ADHD)",
    "components": "sesquiterpenoid",
    "compound": "Valerenic acid",
    "part": "Roots",
    "region_found": "North-Western Himalayan region",
    "reference": "https://assets-us-01.kc-usercontent.com/b3f5510f-b2f6-0081-05a1-dbd7a9328e1f/b279365c-735b-4749-bd59-8a635b3dcd5c/MH%20Herbal%20Neuroplastic%20Support%20Focus%20on%20Neurodegeneration%20and%20Mood%20Disorders.pdf",
    "image": "Valeriana_officinalis.jpeg"
  },
  {
    "scientific_name": "Withania somnifera",
    "common_name": "Ashwagandha",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "Ashwagandholine",
    "part": "Roots",
    "region_found": "sub-tropical regions india",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "withania_somnifera.jpeg"
  },
  {
    "scientific_name": "Zingiber officinale",
    "common_name": "ginger",
    "type_of_disorder": "Alzheimer's disease, enhances memory",
    "components": "Phenolic compound",
    "compound": "6-shogaol",
    "part": "Rhizome",
    "region_found": "southwest and northeast India",
    "reference": "https://www.hindawi.com/journals/bmri/2015/814068/",
    "image": "Zingiber_officinale.jpeg"
  }
]

export const Ayurvedic = [
  {
    "scientific_name": "Acacia farnesiana (L.) Willd.",
    "common_name": "sweet acacia",
    "type_of_disorder": "Vertigo, headache",
    "components": "Alkaloids",
    "compound": "N,N-dimethyltryptamine (DMT)",
    "part": "Flower and leaves",
    "region _found": "tropical regions of India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Acacia_farnesiana_(L.)_Willd.jpeg"
  },
  {
    "scientific_name": "Achyranthes aspera L.",
    "common_name": "prickly chaff flower",
    "type_of_disorder": "Epilepsy, paralysis",
    "components": "Flavanoids",
    "compound": "quercetin, rutin, and kaempferol.",
    "part": "Whole plaant",
    "region _found": "Assam, Bihar, Gujarat, Karnataka, Madhya Pradesh, Odisha, Rajasthan, South India, Uttar Pradesh",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Achyranthes_aspera_L.jpeg"
  },
  {
    "scientific_name": "Acorus calamus",
    "common_name": "sweet flag",
    "type_of_disorder": "ASD",
    "components": "phenylpropanoid",
    "compound": "alpha asarone, beta asarone and eugenol",
    "part": "roots and leaves",
    "region _found": "western Ghat",
    "reference": "https://doi.org/10.33545/27072827.2023.v4.i1a.65",
    "image": "Acorus_calamus.jpeg"
  },
  {
    "scientific_name": "Adhatoda vasica",
    "common_name": "Malabar Nut",
    "type_of_disorder": "ASD",
    "components": "alkaloids, flavanoids",
    "compound": "Vasicine, vasicol, vasicinol, arachidic, cerotic, linoleic, oleic acids",
    "part": "flower and  bark",
    "region _found": "Tropical and Subtropical region of india",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/3.-A-Review-Sanjeev-Mahuda.pdf",
    "image": "Adhatoda_vasica.jpeg"
  },
  {
    "scientific_name": "Aegle marmelos (L.) Correa",
    "common_name": "Bel",
    "type_of_disorder": "Memory loss, schizophrenia, paralysis",
    "components": "Phenolic compound, steroids, coumarin and alkaloids",
    "compound": "Marmelosin, tannic acid, marmesinin, ascorbic acid, eugenol, skimmianine, saponin, aegeline, furocoumarins",
    "part": "Leaves, fruit",
    "region _found": "Himalayan regions, Bengal, Central and South India, and Western Himalaya.",
    "reference": "https://www.bing.com/ck/a?!&&p=3708683ed4ec20ffJmltdHM9MTcxMTA2NTYwMCZpZ3VpZD0wMzkwMGUzYi02Nzg0LTY1NzUtM2EwMy0xYTE0NjY3NjY0ZDEmaW5zaWQ9NTIxOQ&ptn=3&ver=2&hsh=3&fclid=03900e3b-6784-6575-3a03-1a14667664d1&psq=Review+on+ayurvedic+plant+based+compounds+to+cure+the+neurological+disorders+Siba+Pattanaik+and+Deoraj+Sharma&u=a1aHR0cHM6Ly93d3cucmVzZWFyY2hnYXRlLm5ldC9wdWJsaWNhdGlvbi8zNjg2MjIxOTBfUmV2aWV3X29uX2F5dXJ2ZWRpY19wbGFudF9iYXNlZF9jb21wb3VuZHNfdG9fY3VyZV90aGVfbmV1cm9sb2dpY2FsX2Rpc29yZGVycw&ntb=1",
    "image": "Aegle_marmelos_(L.)_Correa.jpeg"
  },
  {
    "scientific_name": "Ageratum conyzoides L.",
    "common_name": "Billy goat weed",
    "type_of_disorder": "Headache, Paralysis (Kh) Vertigo",
    "components": "bicyclic sesquiterpene",
    "compound": "?-caryophyllene",
    "part": "Whole plant",
    "region _found": "Himalayas",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Ageratum_conyzoides_L.jpeg"
  },
  {
    "scientific_name": "Alocasia macrorrhizos (L.)",
    "common_name": "Giant Taro",
    "type_of_disorder": "Mental disorder",
    "components": "phytosterol",
    "compound": "?-sitosterol",
    "part": "plant",
    "region _found": "Andhra Pradesh, Karnataka, Kerala, Maharashtra, Odisha, Lakshwadeep",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Alocasia_macrorrhizos_(L.).jpeg"
  },
  {
    "scientific_name": "Alstonia scholaris (L.) R.Br.",
    "common_name": "Blackboard tree, Devil tree, Milkwood pine, White cheesewood, Scholar tree, Shaitaanwood tree, Dita bark, Bitter bark",
    "type_of_disorder": "schizophrenia",
    "components": "Alkaloids",
    "compound": "Alstonine",
    "part": "Bark",
    "region _found": "West Bengal and the west-coast forests of south India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Alstonia_scholaris_(L.)_R.Br.jpeg"
  },
  {
    "scientific_name": "Andrographis paniculata",
    "common_name": "Kalmegh,green chiretta, serpentina, or king of bitters",
    "type_of_disorder": "Vertigo",
    "components": "Flavanoids",
    "compound": "Andrograpanin",
    "part": "Leaves",
    "region _found": "Madhya Pradesh, Chhattisgarh, Orissa, Maharashtra, Assam, West Bengal, Uttar Pradesh, Tamil Nadu, Kerala",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Andrographis_paniculata.jpeg"
  },
  {
    "scientific_name": "Areca catechu L.",
    "common_name": "reca palm, Chikni supari, Areca nut, Betel quid, and Chalia",
    "type_of_disorder": "Alzheimer's disease, Antidepressant",
    "components": "Alkaloids",
    "compound": "Arecoline",
    "part": "Fruit",
    "region _found": "Kerala, Karnataka and Assam",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Areca_catechu_L.jpeg"
  },
  {
    "scientific_name": "Asparagus racemosus",
    "common_name": "Satawari",
    "type_of_disorder": "anxiety and related disorders",
    "components": "polycyclic alkaloids, flavanoids",
    "compound": "alkaloids (Asparagamine A), Isoflavones-8- methoxy-5, 6, 4-trihydroxy isoflavone-7-0-beta-D-glucopyranoside, Flavonoids (Kaempferol, quercetin, rutin), shatavaroside, secoisolariciresinol, immunosides, beta sitosterol, sitigmaterol, daidzein, genistein, racemoside A-C and other compounds like essential oils, resins, tannins, tyrosine, arginine, asparagine",
    "part": "Root",
    "region _found": "Arunachal Pradesh, Assam, Chhattisgarh, Delhi, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Kerala and Punjab",
    "reference": "https://www.plantsjournal.com/archives/2021/vol9issue4/PartB/9-4-23-980.pdf",
    "image": "Asparagus_racemosus.jpeg"
  },
  {
    "scientific_name": "Azadirachta indica",
    "common_name": "Neem",
    "type_of_disorder": "Alzheimer's disease,",
    "components": "Terpenoid, Flavoinoids, Phenoic",
    "compound": "Azadiradione, Nimbin and Salannin, Limonoids, Gedunin, Quercetin,Salannin, Scopoletin, Arachidic acid, Gallic acid",
    "part": "Neem Extract",
    "region _found": "throughout India, from the southern tip of Kerala to the Himalayan hills, and in tropical to subtropical regions",
    "reference": "https://www.sciencedirect.com/science/article/abs/pii/S0197018621000693",
    "image": "Azadirachta_indica.jpeg"
  },
  {
    "scientific_name": "Bacopa monneri",
    "common_name": "Brahmi",
    "type_of_disorder": "Dementia",
    "components": "Saponins",
    "compound": "Bacosides",
    "part": "Stem and leaves",
    "region _found": "North eastern regions",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Bacopa_monneri.jpeg"
  },
  {
    "scientific_name": "Bauhinia acuminata L.",
    "common_name": "Dwarf White Orchid Tree",
    "type_of_disorder": "Mental disorder, epilepsy",
    "components": "Flavonoids",
    "compound": "Kaempferol, Quercetin ,Rutin ,Apigenin",
    "part": "Root and Flower",
    "region _found": "Kerala, Puri and Khurda districts of Odisha, Kanchipuram district of Tamil Nadu, Doaba region of Punjab,  and in Bardhaman West Bengal.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Bauhinia_acuminata_L.jpeg"
  },
  {
    "scientific_name": "Benincasa hispida (Thunb.) Cogn.",
    "common_name": "Wax Gourd",
    "type_of_disorder": "Epilepsy, nervous system disorder",
    "components": "Triterpenoid",
    "compound": "cucurbitacin B",
    "part": "Seed and Fruit",
    "region _found": "Throughout Assam",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Benincasa_hispida_(Thunb.)_Cogn.jpeg"
  },
  {
    "scientific_name": "Bixa orellana L",
    "common_name": "annatto or achiote",
    "type_of_disorder": "Epilepsy",
    "components": "diterpenoid",
    "compound": "norbixin",
    "part": "Seed",
    "region _found": "Andhra Pradesh, Assam, Kerala, Manipur, Odisha",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Bixa_orellana_L.jpeg"
  },
  {
    "scientific_name": "Blumea balsamifera DC.",
    "common_name": "Ngai camphor and sambong",
    "type_of_disorder": "Headache, insomnia",
    "components": "bicyclic sesquiterpene",
    "compound": "?-caryophyllene",
    "part": "Leaves",
    "region _found": "Assam,manipur, Meghalaya",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Blumea_balsamifera_DC.jpeg"
  },
  {
    "scientific_name": "Boerhaavia diffusa",
    "common_name": "Punarnava",
    "type_of_disorder": "Huntington's Disease",
    "components": "Alkaloids, Phenolic compounds",
    "compound": "Punarnavine, caffeoyltartaric acid",
    "part": "Roots",
    "region _found": "northeastern parts of India, including the Amaravathi village in Guntur district",
    "reference": "https://onlinelibrary.wiley.com/doi/abs/10.1002/9783527803781.ch8",
    "image": "Boerhaavia_diffusa.jpeg"
  },
  {
    "scientific_name": "Borassus flabellifer L.",
    "common_name": "doub palm, palmyra palm, tala palm, toddy palm, wine palm, or ice apple",
    "type_of_disorder": "Epilepsy",
    "components": "Alkaloids",
    "compound": "Triterpenoids",
    "part": "Fruit",
    "region _found": "Tamil Nadu, Andhra Pradesh, Kerala, Karnataka, Maharashtra, Madhya Pradesh, Chhattisgarh, and Odisha.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Borassus_flabellifer_L.jpeg"
  },
  {
    "scientific_name": "Boswellia serrata",
    "common_name": "Indian frankincense, Indian olibanum, Salai guggul, Shallaki, Parangi, Saambraa",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Triterpenes",
    "compound": "pentacyclic triterpene acids, β-boswellic acid and the acetylboswellic acids",
    "part": "Resin",
    "region _found": "Andhra Pradesh, Gujarat, Madhya Pradesh, Jharkhand, and Chhattisgarh",
    "reference": "https://assets-us-01.kc-usercontent.com/b3f5510f-b2f6-0081-05a1-dbd7a9328e1f/b279365c-735b-4749-bd59-8a635b3dcd5c/MH%20Herbal%20Neuroplastic%20Support%20Focus%20on%20Neurodegeneration%20and%20Mood%20Disorders.pdf",
    "image": "Boswellia_serrata.jpeg"
  },
  {
    "scientific_name": "Brassica oleracea L. var. italica",
    "common_name": "Broccoli sprouts",
    "type_of_disorder": "Autism",
    "components": "Isothiocyanate",
    "compound": "Sulforaphane",
    "part": "Broccoli Sprout",
    "region _found": "Tamil Nadu",
    "reference": "https://www.florajournal.com/archives/2021/vol9issue3/PartA/9-1-13-226.pdf",
    "image": "Brassica_oleracea_L_var_italica.jpeg"
  },
  {
    "scientific_name": "Bryophyllum pinnatum Kurz",
    "common_name": "panfuti",
    "type_of_disorder": "Epilepsy, headache (Ma), vertigo",
    "components": "Glycoside",
    "compound": "bufadienolides",
    "part": "Leaves",
    "region _found": "West bengal",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Bryophyllum_pinnatum_Kurz.jpeg"
  },
  {
    "scientific_name": "Caesalpinia crista L.",
    "common_name": "Fever nut",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Alkaloids",
    "compound": "Vasicine",
    "part": "Fruit and seed",
    "region _found": "Along the riverbanks and in the tidal forests that are located close to the Eastern seacoast beginning in Orissa and continuing Southward along the Western seacoast beginning in Konkan.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Caesalpinia_crista_L.jpeg"
  },
  {
    "scientific_name": "Calotropis gigantea (L.) W.T.Aiton",
    "common_name": "Indian milkweed",
    "type_of_disorder": "Alzheimer's disease and Parkinson's disease",
    "components": "Cardenolides",
    "compound": "Calotropin",
    "part": "Shoot",
    "region _found": "Marathwada region of the state of Maharashtra, and in the Marsur area of Anekal Taluk, Bengaluru",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Calotropis_gigantea_(L.)_W.T.Aiton.jpeg"
  },
  {
    "scientific_name": "Cannabis sativa L",
    "common_name": "Hemp",
    "type_of_disorder": "Neurodegenerative diseases, Alzheimer’s disease",
    "components": "Alkaloids",
    "compound": "Tetrahydrocannabinol, Cannabidiol",
    "part": "Leaves",
    "region _found": "Uttarakhand,  Himachal  Pradesh,  Jammu  and  Kashmir,  North  East,  and Madhya Pradesh.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Cannabis_sativa_L.jpeg"
  },
  {
    "scientific_name": "Carissa carandas L.",
    "common_name": "Christ's thorn, Bengal currant, Carandas plum, Jasmine flowered Carissa, Black currant",
    "type_of_disorder": "Insanity, headache",
    "components": "Flavanoids",
    "compound": "quercetin, rutin, and kaempferol",
    "part": "Fruit",
    "region _found": "Bihar, West Bengal, Maharashtra, Karnataka, Rajasthan, Gujarat, and Uttar Pradesh",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Carissa_carandas_L.jpeg"
  },
  {
    "scientific_name": "Celastrus paniculatus Wild",
    "common_name": "Jyotishmati",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "Celastrine",
    "part": "Seeds",
    "region _found": "Punjab, Kashmir, Western Ghats, Eastern Ghats, Rajmahal hills in Bihar and Orissa,  Simlipal Biosphere Reserve Forest, Karlapat Sanctuary, Niyamgiri hills",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Celastrus_paniculatus_Wild.jpeg"
  },
  {
    "scientific_name": "Centella asiatica (L.) Urb.",
    "common_name": "Asiatic pennywort",
    "type_of_disorder": "Memory loss, mental disorder, insanity",
    "components": "Triterpenoids",
    "compound": "asiaticoside, madecassoside, asiatic acid, and madecassic acid",
    "part": "Leaves",
    "region _found": "throughout India growing in moist places up to an altitude of 1800 m.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Centella_asiatica_(L.)_Urb.jpeg"
  },
  {
    "scientific_name": "Cheilocostus speciosus C.D.Specht",
    "common_name": "Crepe ginger",
    "type_of_disorder": "Neuroinflammatory diseases",
    "components": "polyphenolic",
    "compound": "Curcumin",
    "part": "Whole plant",
    "region _found": "Assam, Odisha, Bihar, Meghalaya",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Cheilocostus_speciosus_C.D.Specht.jpeg"
  },
  {
    "scientific_name": "Cissus adnata Roxb.",
    "common_name": "Entire-leaf wild grape, Heart-leaved grape, Endeavour River vine, Gudametake, and Kokkita yaralu",
    "type_of_disorder": "Paralysis (Sa), mental disorder, epilepsy, paralysis",
    "components": "Lipids",
    "compound": "ketosterones",
    "part": "Stem",
    "region _found": "West Bengal, Sikkim, Arunachal Pradesh, Assam, Manipur, Mizoram, Tripura, Meghalaya, and Orissa",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Cissus_adnata_Roxb.jpeg"
  },
  {
    "scientific_name": "Cissus repens Lam.",
    "common_name": "Cissus, Malayan Wild Vine, Carik Merah, Lakum, Pokok Riang Hutan, or Som Toum",
    "type_of_disorder": "Epilepsy, vertigo",
    "components": "flavonoids",
    "compound": "Quercetin",
    "part": "leaves",
    "region _found": "he plains and hills of Assam, Maharashtra, Karnataka, Kerala, and Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Cissus_repens_Lam.jpeg"
  },
  {
    "scientific_name": "Citrullus lanatus (Thunb.) Mansf.",
    "common_name": "watermelon",
    "type_of_disorder": "Neurodegenerative disease",
    "components": "Triterpenoid",
    "compound": "Cucurbitacin E",
    "part": "Seed and Fruit",
    "region _found": "North-Western Plains of the Indo-Gangetic Region (Sub-tropical with Mild Winters), Coastal States of Tamil Nadu, Karnataka, and Orissa",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Citrullus_lanatus_(Thunb.)_Mansf.jpeg"
  },
  {
    "scientific_name": "Citrus grandis Osbeck",
    "common_name": "pomelo",
    "type_of_disorder": "Memory disorders, Alzheimer’s disease",
    "components": "Flavonoids",
    "compound": "3,5,6,7,8,3?,4?-Heptamethoxyflavone",
    "part": "Fruit",
    "region _found": "South India, NE Region",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Citrus_grandis_Osbeck.jpeg"
  },
  {
    "scientific_name": "Clerodendrum infortunatum L.",
    "common_name": "Bhant",
    "type_of_disorder": "Alzheimer’s disease, cognitive deficit",
    "components": "phenylethanoid glycoside",
    "compound": "Acteoside",
    "part": "Leaves",
    "region _found": "Andaman and Nicobar Islands, Assam, Goa, Karnataka, Kerala, Maharashtra, and Tamil Nadu.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Clerodendrum_infortunatum_L.jpeg"
  },
  {
    "scientific_name": "Clitoria ternatea",
    "common_name": "Aparajita",
    "type_of_disorder": "DEMENTIA",
    "components": "amino acids, proteins and carbohydrates",
    "compound": "",
    "part": "Roots",
    "region _found": "Andaman and Nicobar Islands, Andhra Pradesh,Assam, Bihar, Gujarat, Haryana, Karnataka,Kerala, Madhya Pradesh, Maharashtra, Manipur, Rajasthan, Tamil Nadu, Uttar Pradesh, West Bengal",
    "reference": "https://www.researchgate.net/profile/Dilip_Murthy2/publication/10984268_Clitoria_ternatea_root_extract_enhances_acetylcholine_content_in_rat_hippocampus/links/5a3c9d7e0f7e9b10e23bf5fc/Clitoria-ternatea-root-extract-enhances-acetylcholine-content-in-rat-hippocampus.pdf",
    "image": "Clitoria_ternatea.jpeg"
  },
  {
    "scientific_name": "Colchicum autumnale",
    "common_name": "Saffron",
    "type_of_disorder": "ASD",
    "components": "crocins",
    "compound": "carotenoid crocetin",
    "part": "dried stigma",
    "region _found": "kashmir",
    "reference": "https://assets-us-01.kc-usercontent.com/b3f5510f-b2f6-0081-05a1-dbd7a9328e1f/59de9ba6-da7b-460e-ac4a-98a98cf67618/2016w_optimising_cognition_mh_notes_b_w-min.pdf",
    "image": "Colchicum_autumnale.jpeg"
  },
  {
    "scientific_name": "Colocasia esculenta (L.) Schott",
    "common_name": "taro or elephant ear",
    "type_of_disorder": "Nervous system disorder",
    "components": "Lipid",
    "compound": "Beta-sitosterol",
    "part": "Whole plant",
    "region _found": "Northeast region of India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Colocasia_esculenta_(L.)_Schott.jpeg"
  },
  {
    "scientific_name": "Convolvulus pluricaulis",
    "common_name": "Shankhpushpi",
    "type_of_disorder": "Alzheimer’s",
    "components": "Coumarins",
    "compound": "Scopoletin",
    "part": "leaves, flowers, stem, roots, seeds and ashes",
    "region _found": "Bihar and Punjab",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Convolvulus_pluricaulis.jpeg"
  },
  {
    "scientific_name": "Costus speciosus (J.Koenig) Sm.",
    "common_name": "crepe ginger, spiral ginger, or variegated ginger",
    "type_of_disorder": "Neuroinflammatory diseases",
    "components": "Costunolide",
    "compound": "sesquiterpene lactone",
    "part": "Rhizomes",
    "region _found": "Andhra Pradesh, Karnataka, Kerala, Maharashtra, Odisha, Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Costus_speciosus_(J.Koenig)_Sm.jpeg"
  },
  {
    "scientific_name": "Crescentia cujete L.",
    "common_name": "calabash tree",
    "type_of_disorder": "Brain disorder",
    "components": "Triterpenoid",
    "compound": "Cucurbitacin B",
    "part": "Fruit and Bark",
    "region _found": "Delhi, Uttar Pradesh, West Bengal, Assam, Tripura, Madhya Pradesh and Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Crescentia_cujete_L.jpeg"
  },
  {
    "scientific_name": "Curcuma longa",
    "common_name": "Turmeric",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "Curcuminoids",
    "part": "Rhizome",
    "region _found": "Andhra Pradesh, Tamil Nadu, Orissa, Karnataka, West Bengal, Gujarat, Meghalaya, Maharashtra, Assam",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Curcuma_longa.jpeg"
  },
  {
    "scientific_name": "Cyathula prostrata Blume",
    "common_name": "pastureweed, hookweed, and Nyarang.",
    "type_of_disorder": "Epilepsy, headache",
    "components": "Flavanoids",
    "compound": "Quercetin, Kaempferol, Luteolin, Apigenin",
    "part": "Leaves and root",
    "region _found": "Assam, Kerala, Karnataka, Manipur, Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Cyathula_prostrata_Blume.jpeg"
  },
  {
    "scientific_name": "Cyperus rotundus L.",
    "common_name": "Purple nutsedge",
    "type_of_disorder": "Paralysis",
    "components": "Sesquiterpenoid",
    "compound": "?-Cyperone",
    "part": "Root",
    "region _found": "Assam, Madhya Pradesh",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Cyperus_rotundus_L.jpeg"
  },
  {
    "scientific_name": "Datura metel L.",
    "common_name": "Datura",
    "type_of_disorder": "nsanity, schizophrenia, mental disorder",
    "components": "Alkaloids",
    "compound": "scopolamine, hyoscyamine, and atropine",
    "part": "",
    "region _found": "Assam, Bihar, Meghalaya, Odisha, Rajasthan, Uttar Pradesh",
    "reference": "Traditional Herbal Medicines Against CNS Disorders from Bangladesh - PMC",
    "image": "Datura_metel_L.jpeg"
  },
  {
    "scientific_name": "Delphinium denudatum Wall.",
    "common_name": "Jadwar",
    "type_of_disorder": "Anticonvulsants",
    "components": "alkaloids",
    "compound": "Isoxylitone,ethanolic extract",
    "part": "Dried root",
    "region _found": "Northern Western Ghats of Maharashtra",
    "reference": "https://www.researchgate.net/publication/345132007_Jadwar_Delphinium_denudatum_Wall_a_medicinal_plant",
    "image": "Delphinium_denudatum_Wall.jpeg"
  },
  {
    "scientific_name": "Desmodium gangeticum",
    "common_name": "Dirghamuli",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Phenytoin",
    "compound": "indol-3-alkyl-amines and b-carbolines",
    "part": "Flower and leaf",
    "region _found": "plain and western Ghats and north up to Sikkim",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Desmodium_gangeticum.jpeg"
  },
  {
    "scientific_name": "Dillenia indica L.",
    "common_name": "elephant apple or chulta",
    "type_of_disorder": "Epilepsy, headache",
    "components": "Mental disorder, epilepsy",
    "compound": "Quercetin",
    "part": "Fruit",
    "region _found": "North East India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Dillenia_indica_L.jpeg"
  },
  {
    "scientific_name": "Diplazium esculentum (Retz.) Sw",
    "common_name": "Vegetable fern",
    "type_of_disorder": "Headache, epilepsy",
    "components": "Flavonoids",
    "compound": "Quercetin",
    "part": "Leaves",
    "region _found": "Himalayan region",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Diplazium_esculentum_(Retz.)_Sw.jpeg"
  },
  {
    "scientific_name": "Eclipta Alba",
    "common_name": "Bhringraj",
    "type_of_disorder": "Alzheimer disease",
    "components": "phenolic compounds",
    "compound": "coumestan",
    "part": "Plant",
    "region _found": "throughout India, including the Agumbe region of Western Ghats",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Eclipta_Alba.jpeg"
  },
  {
    "scientific_name": "Euphorbia neriifolia L.",
    "common_name": "Indian spurge tree or milk bush",
    "type_of_disorder": "Schizophrenia",
    "components": "tetracyclic diterpenoids",
    "compound": "phorbol esters",
    "part": "Leaves",
    "region _found": "throughout the Orissa and Deccan Peninsula in India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Euphorbia_neriifolia_L.jpeg"
  },
  {
    "scientific_name": "Evolvulus alsinoides L",
    "common_name": "Little Glory",
    "type_of_disorder": "Memory loss, sleeplessness ,epilepsy",
    "components": "Phenolic compound",
    "compound": "arescopoletin, umbelliferone and scopolin",
    "part": "whole plant",
    "region _found": "Andhra Pradesh, Karnataka, Kerala, Maharashtra, Odisha, and Tamil Nadu.",
    "reference": "https://www.bing.com/ck/a?!&&p=3708683ed4ec20ffJmltdHM9MTcxMTA2NTYwMCZpZ3VpZD0wMzkwMGUzYi02Nzg0LTY1NzUtM2EwMy0xYTE0NjY3NjY0ZDEmaW5zaWQ9NTIxOQ&ptn=3&ver=2&hsh=3&fclid=03900e3b-6784-6575-3a03-1a14667664d1&psq=Review+on+ayurvedic+plant+based+compounds+to+cure+the+neurological+disorders+Siba+Pattanaik+and+Deoraj+Sharma&u=a1aHR0cHM6Ly93d3cucmVzZWFyY2hnYXRlLm5ldC9wdWJsaWNhdGlvbi8zNjg2MjIxOTBfUmV2aWV3X29uX2F5dXJ2ZWRpY19wbGFudF9iYXNlZF9jb21wb3VuZHNfdG9fY3VyZV90aGVfbmV1cm9sb2dpY2FsX2Rpc29yZGVycw&ntb=2",
    "image": "Evolvulus_alsinoides_L.jpeg"
  },
  {
    "scientific_name": "Ferula asafoetida L",
    "common_name": "Hing",
    "type_of_disorder": "neurological disorders",
    "components": "Phenolic compound",
    "compound": "carbohydrate and ferulic acid",
    "part": "dried latex, rhizome and root",
    "region _found": "Kashmir and parts of Punjab, and is also available in the Indian Himalayan region",
    "reference": "https://www.bing.com/ck/a?!&&p=3708683ed4ec20ffJmltdHM9MTcxMTA2NTYwMCZpZ3VpZD0wMzkwMGUzYi02Nzg0LTY1NzUtM2EwMy0xYTE0NjY3NjY0ZDEmaW5zaWQ9NTIxOQ&ptn=3&ver=2&hsh=3&fclid=03900e3b-6784-6575-3a03-1a14667664d1&psq=Review+on+ayurvedic+plant+based+compounds+to+cure+the+neurological+disorders+Siba+Pattanaik+and+Deoraj+Sharma&u=a1aHR0cHM6Ly93d3cucmVzZWFyY2hnYXRlLm5ldC9wdWJsaWNhdGlvbi8zNjg2MjIxOTBfUmV2aWV3X29uX2F5dXJ2ZWRpY19wbGFudF9iYXNlZF9jb21wb3VuZHNfdG9fY3VyZV90aGVfbmV1cm9sb2dpY2FsX2Rpc29yZGVycw&ntb=1",
    "image": "Ferula_asafoetida_L.jpeg"
  },
  {
    "scientific_name": "Ficus hispida L.f.",
    "common_name": "Hairy Fig",
    "type_of_disorder": "Epilepsy, paralysis",
    "components": "Flavonoids",
    "compound": "quercetin and kaempferol",
    "part": "Leaves, flower, seed, root, bark",
    "region _found": "throughout India, including in the Western Ghats",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Ficus_hispida_L.f.jpeg"
  },
  {
    "scientific_name": "Foeniculum vulgare Mill",
    "common_name": "common fennel",
    "type_of_disorder": "Cognitive function and memory",
    "components": "phenylpropene",
    "compound": "Anethole",
    "part": "Fruits and seed",
    "region _found": "Gujarat, Rajasthan, Karnataka, Maharashtra, Punjab, and Bihar",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Foeniculum_vulgare_Mill.jpeg"
  },
  {
    "scientific_name": "Ginkgo biloba",
    "common_name": "ginkgo",
    "type_of_disorder": "schizophrenia",
    "components": "Terpenoids, flavonoids and proanthocyanidins",
    "compound": "quercetin, catechin, ginkgolides and bilobalides,",
    "part": "leaf",
    "region _found": "Northeast India",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1596191837.pdf",
    "image": "Ginkgo_biloba.jpeg"
  },
  {
    "scientific_name": "Glycirrhiza glabra",
    "common_name": "Yashtimadhu",
    "type_of_disorder": "CNS disorder,oxidative stress,",
    "components": "flavonoids",
    "compound": "isoflavones, glabridin and hispalglabridins A and B",
    "part": "stem",
    "region _found": "forests of western and central India",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1522479026.pdf",
    "image": "Glycirrhiza_glabra.jpeg"
  },
  {
    "scientific_name": "Hemidesmus indicus (L.) R.Br.",
    "common_name": "Indian sarsaparilla",
    "type_of_disorder": "Mental disorder, nervous debility, heat stroke",
    "components": "Alkaloids",
    "compound": "hemidesmine and hemidine",
    "part": "Leaves and root",
    "region _found": "south India and west Bengal",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Hemidesmus_indicus_(L.)_R.Br.jpeg"
  },
  {
    "scientific_name": "Hyoscyamus Niger",
    "common_name": "black henbane",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "hyoscyamine, scopolamine and tropane",
    "part": "Flower",
    "region _found": "assam and arunachal pradesh",
    "reference": "https://doi.org/10.33545/27072827.2023.v4.i1a.65",
    "image": "Hyoscyamus_Niger.jpeg"
  },
  {
    "scientific_name": "Hypericum perforatum",
    "common_name": "St. John's wort",
    "type_of_disorder": "schizophrenia",
    "components": "naphthodianthrones, phloroglucinols, and flavonoids",
    "compound": "phenylpropanes, flavonol glycosides, and biflavones,hypericin and hyperforin",
    "part": "flowers and leaf",
    "region _found": "Temperate regions.",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1596191837.pdf",
    "image": "Hypericum_perforatum.jpeg"
  },
  {
    "scientific_name": "Ipomoea aquatica Forssk.",
    "common_name": "Water spinach",
    "type_of_disorder": "CNS depressant, memory and Alzheimer’s disease",
    "components": "Flavonoids",
    "compound": "kaempferol",
    "part": "Whole plant",
    "region _found": "Assam, Bihar, Madhya Pradesh, Odisha, Rajasthan, Uttar Pradesh",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Ipomoea_aquatica_Forssk.jpeg"
  },
  {
    "scientific_name": "Justicia gendarussa",
    "common_name": "illow-leaved justicia",
    "type_of_disorder": "Paralysis",
    "components": "Flavanoids",
    "compound": "kaempferol and quercetin",
    "part": "Leaves",
    "region _found": "throughout the river beds of Southern India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Justicia_gendarussa.jpeg"
  },
  {
    "scientific_name": "Kalanchoe pinnata (Lam.) Pers.",
    "common_name": "Air Plant",
    "type_of_disorder": "Epilepsy, headache",
    "components": "Glycoside",
    "compound": "bufadienolides",
    "part": "Leaves",
    "region _found": "Maharashtra, Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Kalanchoe_pinnata_(Lam.)_Pers.jpeg"
  },
  {
    "scientific_name": "Lawsonia inermis L.",
    "common_name": "henna",
    "type_of_disorder": "epilepsy",
    "components": "polycyclic aromatic hydrocarbon",
    "compound": "Lawsone (2-hydroxy-1,4-naphthoquinone)",
    "part": "Leaves",
    "region _found": "Rajasthan, Gujarat, Madhya Pradesh and Punjab.",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Lawsonia_inermis.jpeg"
  },
  {
    "scientific_name": "Litsea polyantha Juss.",
    "common_name": "Indian laurel",
    "type_of_disorder": "Schizophrenia",
    "components": "Terpene alcohol",
    "compound": "Linalool",
    "part": "Bark",
    "region _found": "North, East, and Central India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Litsea_polyantha.jpeg"
  },
  {
    "scientific_name": "Mimosa pudica L.",
    "common_name": "touch-me-not",
    "type_of_disorder": "Insomnia",
    "components": "Alkaloids",
    "compound": "mimosine",
    "part": "Whole plant",
    "region _found": "Assam, Bihar, Kerala, Madhya Pradesh, Maharastra, Manipur, Mysore, Odisha, Rajasthan, Tamil Nadu, West Bengal",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Mimosa_pudica_L.jpeg"
  },
  {
    "scientific_name": "Morinda citrifolia L.",
    "common_name": "Noni",
    "type_of_disorder": "Schizophrenia",
    "components": "Phenolic compound",
    "compound": "Scopoletin",
    "part": "Fruit and leaves",
    "region _found": "Konkan region of India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Morinda_citrifolia_L.jpeg"
  },
  {
    "scientific_name": "Moringa oleifera",
    "common_name": "drumstick tree",
    "type_of_disorder": "DEMENTIA",
    "components": "phenolic compounds and flavonoids",
    "compound": "",
    "part": "Leaves",
    "region _found": "Northwest India",
    "reference": "https://rjpls.com/wp-content/uploads/2023/05/2.-A-PROMISING-APPROACH-FOR-THE-TREATMENT-BY-DEMENTIA-DISEASE-WITH-THE-HELP-OF-HERBAL-DRUGS.pdf",
    "image": "Moringa_oleifera.jpeg"
  },
  {
    "scientific_name": "Mucuna pruriens DC.",
    "common_name": "velvet bean",
    "type_of_disorder": "Neuroprotection for Parkinson's disease",
    "components": "Alkaloids",
    "compound": "5-HTP (5-hydroxytryptophan)",
    "part": "Root and Seed",
    "region _found": "throughout India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Mucuna_pruriens_DCh.jpeg"
  },
  {
    "scientific_name": "Nardostachys jatamansi",
    "common_name": "Sugandhbala",
    "type_of_disorder": "psychotic disorders",
    "components": "Flavonoids",
    "compound": "4-amino-5-mercapto-3-substituted-1, 2, 4-triazole",
    "part": "Root Extract",
    "region _found": "subtropical and temperate Himalaya",
    "reference": "https://www.researchgate.net/publication/281550536_DIETARY_SUPPLEMENTATION_OF_NATURAL_AND_SYNTHETIC_PRODUCTS_REDUCES_ANXIETY_IN_MICE_AGAINST_ELECTRON_BEAM_RADIATION_INDUCED_OXIDATIVE_STRESS",
    "image": "Nardostachys_jatamansi.jpeg"
  },
  {
    "scientific_name": "Nelumbo nucifera Gaertn.",
    "common_name": "Lotus",
    "type_of_disorder": "Nervous debility",
    "components": "Alkaloids, Flavonoids, Phenolic compounds",
    "compound": "Alkaloids(Nuciferine), Flavonoids(quercetin and kaempferol), Phenolic compound(Gallic acid)",
    "part": "Whole plant",
    "region _found": "central and northern India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Nelumbo_nucifera_Gaertn.jpeg"
  },
  {
    "scientific_name": "Nigella sativa L.",
    "common_name": "Black seed, black cumin, kalonji",
    "type_of_disorder": "Epilepsy",
    "components": "Phenolic compound",
    "compound": "Thymoquinone",
    "part": "Fruit",
    "region _found": "Punjab, Himachal Pradesh, Madhya Pradesh, Assam, West Bengal, Jharkhand, and Bihar",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Nigella_sativa_L.jpeg"
  },
  {
    "scientific_name": "Ocimum gratissimum L.",
    "common_name": "Tulsi or clove basil",
    "type_of_disorder": "Paralysis, mental disorder (Be), headache",
    "components": "phenylpropanoid",
    "compound": "Eugenol",
    "part": "Leaves and seed",
    "region _found": "Kerala",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Ocimum_gratissimum_L.jpeg"
  },
  {
    "scientific_name": "Opuntia dillenii Haw.",
    "common_name": "prickly pear cactus",
    "type_of_disorder": "Neurodegenerative disease",
    "components": "Alkaloids",
    "compound": "betalains",
    "part": "Leaves",
    "region _found": "Assam, Bihar, Tamil Nadu, Rajasthan",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Opuntia_dillenii_Haw.jpeg"
  },
  {
    "scientific_name": "Oroxylum indicum (L.) Benth.",
    "common_name": "Shyonaka",
    "type_of_disorder": "Mental disorder",
    "components": "Flavonoids",
    "compound": "Baicalein",
    "part": "Stem",
    "region _found": "North East India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Oroxylum_indicum_(L.)_Benth.jpeg"
  },
  {
    "scientific_name": "Passiflora foetida L.",
    "common_name": "Stinking passionflower",
    "type_of_disorder": "Epilepsy",
    "components": "Alkaloids",
    "compound": "harmine, harmaline, and harman",
    "part": "Leaves",
    "region _found": "throughout the state of Odisha in India, and in all districts of Kerala",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Passiflora_foetida_L.jpeg"
  },
  {
    "scientific_name": "Passiflora incarnata",
    "common_name": "maypop",
    "type_of_disorder": "anxiety and related disorders",
    "components": "alkaloids, flavanoids",
    "compound": "alkaloids(harmol, harman, harmine, harmaline and harmalol, flavonoids (Chrysin, \nbenzoflavone, apigenin, orientin, isoorientin, vitexin, and isovitexin)",
    "part": "Leaves and stem",
    "region _found": "North East region of India",
    "reference": "https://www.plantsjournal.com/archives/2021/vol9issue4/PartB/9-4-23-980.pdf",
    "image": "Passiflora_incarnata.jpeg"
  },
  {
    "scientific_name": "Persicaria hydropiper (L.) Delarbre",
    "common_name": "Water pepper",
    "type_of_disorder": "Epilepsy",
    "components": "Alkaloids",
    "compound": "Piperine",
    "part": "Whole plant",
    "region _found": "Kerala : Wayanad district, Malappuram district, Thrissur district, Kottayam district, Alappuzha district, Idukki district,Tamil Nadu : Coimbatore district, Dindigul district, The Nilgiri district",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Persicaria_hydropiper_(L.)_Delarbre.jpeg"
  },
  {
    "scientific_name": "Phoenix sylvestris (L.) Roxb",
    "common_name": "Indian date, Silver date palm, Toddy palm, and Khajuri.",
    "type_of_disorder": "Nervous debilit",
    "components": "steroidal alkaloids",
    "compound": "Saponins",
    "part": "Fruit,root",
    "region _found": "Southern India: Karnataka, Kerala, Tamil Nadu, Andhra Pradesh Western India: Maharashtra, Gujarat, Rajasthan Eastern India: West Bengal, Odisha, Bihar Northern India: Uttar Pradesh, Punjab, Haryana, Himachal Pradesh",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Phoenix_sylvestris_(L.)_Roxb.jpeg"
  },
  {
    "scientific_name": "Phyllanthus emblica L.",
    "common_name": "Amla",
    "type_of_disorder": "Epilepsy, Alzheimer's disease, memory enhance",
    "components": "polyphenolic compounds",
    "compound": "Tannins",
    "part": "Fruit",
    "region _found": "central and southern India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Phyllanthus_emblica_L.jpeg"
  },
  {
    "scientific_name": "Piper betel Blanco",
    "common_name": "Pan",
    "type_of_disorder": "Cognitive dysfunction",
    "components": "phenylpropanoid",
    "compound": "Hydroxychavicol",
    "part": "Whole plant",
    "region _found": "Bengal, Bihar, Orissa, Andhra Pradesh, Karnataka, Uttar Pradesh, and Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Piper_betel_Blanco.jpeg"
  },
  {
    "scientific_name": "Piper cubeba L.f.",
    "common_name": "Cubeb or Java pepper",
    "type_of_disorder": "Headache, mental disorder",
    "components": "sesquiterpene alcohol",
    "compound": "cubebol",
    "part": "Fruit",
    "region _found": "Kodagu (Coorg) district of Karnataka, India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Piper_cubeba_L.jpeg"
  },
  {
    "scientific_name": "Piper longum L",
    "common_name": "Indian long pepper",
    "type_of_disorder": "Neuroprotective, Parkinson's disease",
    "components": "Alkaloids",
    "compound": "piperlongumine, piperine, pellitorine, and sesquiterpenes",
    "part": "Leaves and root",
    "region _found": "Khasi hills, the lower hills of West Bengal, Eastern Uttar Pradesh,Madhya Pradesh, Maharashtra, Kerala, Karnataka and Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Piper_longum_L.jpeg"
  },
  {
    "scientific_name": "Piper methysticum",
    "common_name": "Kava",
    "type_of_disorder": "schizophrenia.",
    "components": "kavalactones",
    "compound": "Kavain and Kavapyrone",
    "part": "root extract",
    "region _found": "pacific island",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1596191837.pdf",
    "image": "Piper_methysticum.jpeg"
  },
  {
    "scientific_name": "Portulaca oleracea",
    "common_name": "luni-bhaji or kulfa",
    "type_of_disorder": "CNS Disorders",
    "components": "alpha-linolenic acid (ALA)",
    "compound": "Omega-3 fatty acid",
    "part": "leaves",
    "region _found": "India",
    "reference": "https://www.thepharmajournal.com/archives/?year=2019&vol=8&issue=6&ArticleId=3554",
    "image": "Portulaca_oleracea.jpeg"
  },
  {
    "scientific_name": "Premna corymbosa Merr.",
    "common_name": "Lagaspari",
    "type_of_disorder": "Neurological problem",
    "components": "Alkaloids",
    "compound": "Premnine",
    "part": "Root",
    "region _found": "Kerala, District/s: Kottayam, Kannur, Kozhikkode, Kasaragode, Thrissur, Ernakulam",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "premna_corymbosa.jpeg"
  },
  {
    "scientific_name": "Rauvolfia serpentina Benth.",
    "common_name": "Indian Snakeroot",
    "type_of_disorder": "Epilepsy, insanity, vertigo, schizophrenia",
    "components": "Alkaloids",
    "compound": "Reserpine",
    "part": "Leaves and root",
    "region _found": "The sub-Himalayan tract from Himachal Pradesh eastwards to Sikkim and Bhutan, Assam The lower hills of the Gangetic plains, The eastern and western ghats, Some parts of central India, The Andamans",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Rauvolfia_serpentina_Benth.jpeg"
  },
  {
    "scientific_name": "Rauwolfia serpentina",
    "common_name": "Indian snakeroot, serpentine wood, sarpagandha, Patalagardi, and Chotachand",
    "type_of_disorder": "hypertension, tachycardia, and thyrotoxicosis",
    "components": "Alkaloids",
    "compound": "Reserpine, canescine, deserpidine, recanescine, and rescinnamine",
    "part": "whole plant",
    "region _found": "the sub-Himalayan region, Assam, the lower hills of the Gangetic plains, the eastern and western ghats, some parts of central India, and the Andamans.",
    "reference": "https://wjpr.net/public/abstract_show/12456",
    "image": "Rauwolfia_serpentina.jpeg"
  },
  {
    "scientific_name": "Rhodiola rosea",
    "common_name": "arctic root or golden root",
    "type_of_disorder": "psychotic disorders.",
    "components": "Phenylpropanoids,Phenylethanol derivatives,Flavanoids,Terpenoid,Phenolic acids:",
    "compound": "apomorphine,dizocilpine",
    "part": "root extract",
    "region _found": "Ladakh mountains",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1596191837.pdf",
    "image": "Rhodiola_rosea.jpeg"
  },
  {
    "scientific_name": "Rhynchosia rufescens.",
    "common_name": "Rusty Snoutbean",
    "type_of_disorder": "Autism",
    "components": "synthesized AgNPs",
    "compound": "synthesized AgNPs",
    "part": "seed",
    "region _found": "Kerala and Karnataka",
    "reference": "https://pubmed.ncbi.nlm.nih.gov/31773523/",
    "image": "Rhynchosia_rufescens.jpeg"
  },
  {
    "scientific_name": "Rosmarinus officinalis L.",
    "common_name": "Rosemary",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Phenolic compound",
    "compound": "Rosmarinic acid",
    "part": "leaves",
    "region _found": "Subtropical region of north India",
    "reference": "https://www.researchgate.net/publication/340403948_In_vitro_Screening_for_Acetylcholinesterase_Inhibition_and_Antioxidant_Potential_in_Different_Extracts_of_Sage_Salvia_officinalis_L_and_Rosemary_Rosmarinus_officinalis_L",
    "image": "Rosmarinus_officinalis_L.jpeg"
  },
  {
    "scientific_name": "Ruta angustifolia Pers.",
    "common_name": "narrow-leaved fringed rue",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Alkaloids",
    "compound": "Graveolinine",
    "part": "whole plant",
    "region _found": "throughout india",
    "reference": "https://www.mdpi.com/2223-7747/12/4/827",
    "image": "Ruta_angustifolia_Pers.jpeg"
  },
  {
    "scientific_name": "Salvia officinalis L.",
    "common_name": "sage, culinary sage, garden sage, kitchen sage, and Dalmatian sage",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Phenolic compound",
    "compound": "Rosmarinic acid",
    "part": "leaves",
    "region _found": "North Western Himalayan region of India",
    "reference": "https://www.researchgate.net/publication/340403948_In_vitro_Screening_for_Acetylcholinesterase_Inhibition_and_Antioxidant_Potential_in_Different_Extracts_of_Sage_Salvia_officinalis_L_and_Rosemary_Rosmarinus_officinalis_L",
    "image": "Salvia_officinalis_L.jpeg"
  },
  {
    "scientific_name": "Santalum album L.",
    "common_name": "sandalwood, Indian sandalwood, or Chandana",
    "type_of_disorder": "Mental disorder, epilepsy, headache",
    "components": "Terpenoid",
    "compound": "α-Santalol",
    "part": "Stem",
    "region _found": "Karnataka, Kerala, Madhya Pradesh, and Maharashtra",
    "reference": "Traditional Herbal Medicines Against CNS Disorders from Bangladesh - PMC",
    "image": "Santalum_album_L.jpeg"
  },
  {
    "scientific_name": "Schefflera roxburghii Gamble",
    "common_name": "ginseng, aralia, or ivy family",
    "type_of_disorder": "Insomnia",
    "components": "Lipid",
    "compound": "Beta-sitosterol",
    "part": "Leaves",
    "region _found": "Western Ghats Evergreen Forests",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Schefflera_roxburghii_Gamble.jpeg"
  },
  {
    "scientific_name": "Scoparia dulcis L.",
    "common_name": "Sweet broom weed",
    "type_of_disorder": "Nerve system disorder",
    "components": "Flavonoid glycoside",
    "compound": "Scutellarin, Luteolin",
    "part": "Root and fruit",
    "region _found": "Andhra Pradesh : Throughout Eastern Ghats, Kerala : All districts of Kerala, Odisha : Throughout Odisha, Tamil Nadu : Salem district, Dindigul district, Tiruvannamalai district",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Scoparia_dulcis_L.jpeg"
  },
  {
    "scientific_name": "Semecarpus anacardium L.f.",
    "common_name": "marking nut",
    "type_of_disorder": "Nervous debility",
    "components": "phenolic compounds",
    "compound": "Bhilawanols",
    "part": "Fruit",
    "region _found": "tropical and central parts of India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Semecarpus_anacardium_L.f.jpeg"
  },
  {
    "scientific_name": "Senna tora Roxb.",
    "common_name": "Sicklepod",
    "type_of_disorder": "Alzheimer's disease",
    "components": "glycosides",
    "compound": "Sennosides",
    "part": "Leaves",
    "region _found": "Assam",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Senna_tora_Roxb.jpeg"
  },
  {
    "scientific_name": "Sida acuta Burm.f.",
    "common_name": "common wireweed, teaweed, or ironweed",
    "type_of_disorder": "Nervous system disorder",
    "components": "Alkaloids",
    "compound": "phedrine and vasicinone",
    "part": "Leaves",
    "region _found": "Andhra Pradesh, Karnataka, Kerala, Maharashtra, Andaman and Nicobar Islands, Arunachal Pradesh, Assam, and Bihar",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Sida_acuta_Burm.f.jpeg"
  },
  {
    "scientific_name": "Sida cordifolia L.",
    "common_name": "bala, flannel weed, heart-leaf sida, country mallow, Indian country mallow, white burr, 'ilima, and flannel weed.",
    "type_of_disorder": "Parkinson's disease",
    "components": "Alkaloids",
    "compound": "ephedrine",
    "part": "leaves and bark of roots",
    "region _found": "tropical and subtropical regions of India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Sida_cordifolia_L.jpeg"
  },
  {
    "scientific_name": "Spinacia oleracea",
    "common_name": "spinach",
    "type_of_disorder": "locomotor activity, stereotype behaviors,immobility duration and memory retention",
    "components": "alkaloids,flavanoids,phenoic compounds,proteins ,vitamins etc",
    "compound": "ascorbic acid, apigenin, astragalin, caffeic, lutein, β-carotene, ferulic acid,kampeferol, rutin, querecetin, myricetin, luteolin, ortho-coumaric acid, para-coumaric acid, stigmasterol, protocatechuic acids, methylenedioxy flavonol, glycoglycerolipids, 20-hydroxyecdysone, vitamins, spirasaponins violaxanthin etc.,",
    "part": "seed extract",
    "region _found": "Maharashtra, West Bengal, Gujarat, Andhra Pradesh,Telangana, Kerala, Tamil Nadu, Karnataka and Uttar Pradesh.",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1596191837.pdf",
    "image": "Spinacia_oleracea.jpeg"
  },
  {
    "scientific_name": "Stephania japonica (Thunb.) Miers",
    "common_name": "snake vine",
    "type_of_disorder": "Paralysis (Ch), vertigo, mental disorder",
    "components": "Alkaloids",
    "compound": "Tetrandrine",
    "part": "Leaves",
    "region _found": "Arunachal Pradesh, Assam, Karnataka, Kerala, Maharashtra, Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Stephania_japonica_(Thunb.)_Miers.jpeg"
  },
  {
    "scientific_name": "Synedrella nodiflora Gaertn.",
    "common_name": "Cinderella Weed",
    "type_of_disorder": "Vertigo",
    "components": "Flavonoids",
    "compound": "Luteolin",
    "part": "Leaves and stem",
    "region _found": "Plains of India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Synedrella_nodiflora_Gaertn.jpeg"
  },
  {
    "scientific_name": "Tabernaemontana divaricata (L.) R.Br.",
    "common_name": "Pinwheel Flower",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Alkaloids",
    "compound": "Voacangine, Coronaridine, Tabernanthine, Ibogaine",
    "part": "Leaves, flower and root",
    "region _found": "tropical areas of India,the Western Ghats and evergreen forests",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Tabernaemontana_divaricata_(L.)_R.Br.jpeg"
  },
  {
    "scientific_name": "Terminalia arjuna (Roxb.) Wight & Arn.",
    "common_name": "Arjun Tree",
    "type_of_disorder": "Nervous debility",
    "components": "Triterpenoid saponin",
    "compound": "arjunolic acid",
    "part": "Bark",
    "region _found": "Uttar Pardesh, South Bihar, Madhya Pradesh, Delhi and Deccan region",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Terminalia_arjuna_(Roxb.)_Wight_&_Arn.jpeg"
  },
  {
    "scientific_name": "Terminalia chebula Retz",
    "common_name": "Haritaki",
    "type_of_disorder": "Brain disorder",
    "components": "Phenolic",
    "compound": "Chebulic acid",
    "part": "Fruit",
    "region _found": "Sub-Himalayan region",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Terminalia_chebula_Retz.jpeg"
  },
  {
    "scientific_name": "Thespesia populnea",
    "common_name": "Indian tulip tree",
    "type_of_disorder": "ASD",
    "components": "Acetic acid and ehtanol",
    "compound": "N,N-dimethyl glycine",
    "part": "Flower",
    "region _found": "Karnataka and Tamil Nadu.",
    "reference": "https://www.multidisciplinaryjournal.in/assets/archives/2018/vol3issue2/3-2-21-682.pdf",
    "image": "Thespesia_populnea.jpeg"
  },
  {
    "scientific_name": "Thevetia peruviana",
    "common_name": "yellow oleander",
    "type_of_disorder": "Schizophrenia",
    "components": "cardiac glycosides",
    "compound": "thevetin A, thevetin B, neriifolin, peruvoside, thevetoxin",
    "part": "Bark, seed",
    "region _found": "throughout India",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Thevetia_peruviana.jpeg"
  },
  {
    "scientific_name": "Tinospora cordifolia",
    "common_name": "Guduchi",
    "type_of_disorder": "Anti-stress,Memory enhancer",
    "components": "Alkaloids",
    "compound": "Palmatine",
    "part": "Root",
    "region _found": "tropical Indian subcontinent",
    "reference": "https://www.researchgate.net/publication/310790529_Prevention_Management_of_Autism_-_An_Ayurvedic_Perspective",
    "image": "Tinospora_cordifolia.jpeg"
  },
  {
    "scientific_name": "Trema orientalis (L.) Blume",
    "common_name": "Charcoal-tree",
    "type_of_disorder": "Nervous debility",
    "components": "Alkaloids",
    "compound": "Triterpenoids",
    "part": "Whole plant",
    "region _found": "Andaman & Nicobar Islands, Assam, Bihar, Kerala, Maharashtra, Madhya, Pradesh, Odisha and Tamil Nadu",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Trema_orientalis_(L.)_Blume.jpeg"
  },
  {
    "scientific_name": "Typhonium trilobatum (L.) Schott",
    "common_name": "Bengal Arum or Keladi",
    "type_of_disorder": "Nervous debility, mental disorder",
    "components": "Alkaloids",
    "compound": "Typhonium trilobatum",
    "part": "Whole plant",
    "region _found": "Assam",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Typhonium_trilobatum_(L.)_Schott.jpeg"
  },
  {
    "scientific_name": "Valeriana officinalis",
    "common_name": "garden heliotrope, common valerian, and all-heal",
    "type_of_disorder": "Attention Deficit Hyperactivity Disorder (ADHD)",
    "components": "sesquiterpenoid",
    "compound": "Valerenic acid",
    "part": "Roots",
    "region _found": "North-Western Himalayan region",
    "reference": "https://assets-us-01.kc-usercontent.com/b3f5510f-b2f6-0081-05a1-dbd7a9328e1f/b279365c-735b-4749-bd59-8a635b3dcd5c/MH%20Herbal%20Neuroplastic%20Support%20Focus%20on%20Neurodegeneration%20and%20Mood%20Disorders.pdf",
    "image": "Valeriana_officinalis.jpeg"
  },
  {
    "scientific_name": "Vitex negundo L.",
    "common_name": "Chastetree",
    "type_of_disorder": "Schizophrenia, headache",
    "components": "Terpenoid",
    "compound": "Vitexin",
    "part": "Leaves",
    "region _found": "Assam",
    "reference": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7648845/",
    "image": "Vitex_negundo_L.jpeg"
  },
  {
    "scientific_name": "Withania somnifera",
    "common_name": "Ashwagandha",
    "type_of_disorder": "DEMENTIA",
    "components": "Alkaloids",
    "compound": "Ashwagandholine",
    "part": "Roots",
    "region _found": "sub-tropical regions india",
    "reference": "Review Article A PROMISING APPROACH FOR THE TREATMENT BY DEMENTIA DISEASE WITH THE HELP OF HERBAL DRUGS",
    "image": "withania_somnifera.jpeg"
  },
  {
    "scientific_name": "Xanthosoma violaceum Schott",
    "common_name": "Arrowleaf elephant's ear",
    "type_of_disorder": "Alzheimer's disease",
    "components": "Flavonoids",
    "compound": "Anthocyanins",
    "part": "Tuber",
    "region _found": "Andhra Pradesh, Kerala, Karnataka, and Tamil.",
    "reference": "Traditional Herbal Medicines Against CNS Disorders from Bangladesh - PMC",
    "image": "Xanthosoma_violaceum_Schott.jpeg"
  },
  {
    "scientific_name": "Xylosma longifolia Clos.",
    "common_name": "Long leaved xylosma",
    "type_of_disorder": "Autism, anti-convulsant, anti-depressant,",
    "components": "alkaloids,flavonoids, phenols, tannins, terpenoids and saponins.",
    "compound": "N, N-dimethylglycine",
    "part": "leaves",
    "region _found": "the North-eastern region of India.",
    "reference": "https://nowgonggirlscollege.edu.in/upload/publication_scopus/1652535320.pdf",
    "image": "Xylosma_longifolia_Clos.jpeg"
  },
  {
    "scientific_name": "Ziziphus jujube",
    "common_name": "jujube",
    "type_of_disorder": "schizophrenia",
    "components": "saponins,jujubosides and triterpenoic acids.",
    "compound": "5-HTP, tryptophan, serotonin and theanine",
    "part": "Fruit",
    "region _found": "Maharashtra, Gujarat, Madhya Pradesh, Punjab, Haryana, Rajasthan, Bihar, Karnataka, Andhra Pradesh, Tamil Nadu, West Bengal and Assam.",
    "reference": "https://wjpr.s3.ap-south-1.amazonaws.com/article_issue/1596191837.pdf",
    "image": "Ziziphus_jujube.jpeg"
  }
]